version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: task-sync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task-sync"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  goapp:
    build:
      context: .
      dockerfile: Dockerfile.goapp
    depends_on:
      - postgres

    environment:
      # Рабочее окружение
      ENV: local

      # Настройки сервера
      SERVER_HOST: 0.0.0.0  
      SERVER_PORT: 8080

      # Настройки базы данных PostgreSQL
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: task-sync
      DB_SSLMODE: disable
      DB_DELAY: 5
      DB_ATTEMPTS: 5

      DB_USERNAME: postgres
      DB_PASSWORD: 12345

    ports:
      - "8080:8080"
    volumes:
      - ./migrations:/migrations
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
